FROM adelmofilho/r-base:3.6.2

RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('adelmofilho/Weather-Report)"

WORKDIR artifacts

COPY artifacts/settings.json settings.json
COPY artifacts/keys_tokens.json keys_tokens.json

CMD R -e "weatherReport::generate_token()"
