FROM adelmofilho/r-base:3.6.2

RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_github('adelmofilho/Weather-Report')

WORKDIR /home

COPY artifacts/settings.json /home/artifacts/settings.json
COPY artifacts/keys_tokens.json /home/artifacts/keys_tokens.json

CMD R -e "weatherReport::generate_token('/home/artifacts/settings.json')"


